<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Zuijin.Application\Zuijin.Application.csproj" />
    <ProjectReference Include="..\Zuijin.Domain\Zuijin.Domain.csproj" />
    <ProjectReference Include="..\Zuijin.Infrastructure\Zuijin.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
