<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>7e212a78-dc32-45d9-89f5-bdd303b9e419</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zuijin.AspNetCore\Zuijin.AspNetCore.csproj" />
    <ProjectReference Include="..\Zuijin.Infrastructure\Zuijin.Infrastructure.csproj" />
    <ProjectReference Include="..\Zuijin.Application\Zuijin.Application.csproj" />
    <ProjectReference Include="..\Zuijin.Domain\Zuijin.Domain.csproj" />
  </ItemGroup>

</Project>
